import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/provider/AuthProvider";
import React from "react";
import {Navbar} from "@/components/Navbar";
import {Footer} from "@/components/Footer";
import {Sidebar} from "@/components/Sidebar";
import {isTokenValid, loadToken} from "@/lib/utils";
import {getCurrentUser} from "@/service/auth";
import {User} from "@/service/schema/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex flex-col min-h-screen">
        <Navbar/>
        <div className="flex flex-1">
          <Sidebar/>
          <main className="flex-1 p-4">
            {children}
          </main>
        </div>
        <Footer/>
      </div>
      </body>
      </html>
    </AuthProvider>
  );
}
