import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/provider/AuthProvider";
import React from "react";
import {Navbar} from "@/components/Navbar";
import {Footer} from "@/components/Footer";
import {AppSidebar} from "@/components/AppSidebar";
import {SidebarProvider} from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <AuthProvider>
      <SidebarProvider defaultOpen={false}>
        <AppSidebar/>
        <div className="size-full min-h-screen flex flex-col">
          <Navbar/>
          <div className="flex flex-1">
            <main className="flex-1 p-4 ">
              {children}
            </main>
          </div>
          <Footer/>
        </div>
      </SidebarProvider>
    </AuthProvider>
    </body>
    </html>
  );
}
